export const app_data = { appName: "My Chat" };

export const usersData = [
  {
    id: 1,
    phone: "9337323750",
    name: "Kartik Chandra Sahu",
    gender: "male",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 2,
    phone: "9337323750",
    name: "Kartik Chandra Sahu",
    gender: "male",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 3,
    phone: "9337323750",
    name: "Kartik Chandra Sahu",
    gender: "male",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 4,
    phone: "9337323750",
    name: "Riya Tiwari",
    gender: "female",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 5,
    phone: "9337323750",
    name: "Riya Tiwari",
    gender: "female",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 6,
    phone: "9337323750",
    name: "Riya Tiwari",
    gender: "female",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 7,
    phone: "9337323750",
    name: "Riya Tiwari",
    gender: "female",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 8,
    phone: "9337323750",
    name: "Riya Tiwari",
    gender: "female",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 9,
    phone: "9337323750",
    name: "Shubham Tiwari",
    gender: "male",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 10,
    phone: "9337323750",
    name: "Shubham Tiwari",
    gender: "male",
    avatar: "",
    chat: [],
    status: [],
  },
  {
    id: 11,
    phone: "9337323750",
    name: "Vivek Tiwari",
    gender: "male",
    avatar: "",
    chat: [],
    status: [],
  },
];
